services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      KEYCLOAK_URL: ${KEYCLOAK_URL}
      REDIRECT_URL: ${REDIRECT_URL}
      REALM: ${REALM}
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET_KEY: ${CLIENT_SECRET_KEY}
    depends_on:
      - keycloak
      - db

  nginx_frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "8080:80"

  keycloak:
    image: quay.io/keycloak/keycloak:20.0.1
    restart: always
    command: start-dev
    ports:
      - "8099:8080"
    env_file:
      - .env
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    volumes:
      - data:/opt/keycloak/data/
  db:
    image: postgres:15-alpine
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  data:
  postgres_data:
