route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'telegram'

receivers:
- name: 'telegram'
  telegram_configs:
  - bot_token: '7963248231:AAFqEqDBvdBhhvCzmHRQT6FBo9Pz3PhCGf4'  # Токен бота
    chat_id: 1213158996                                   # Chat ID 
    api_url: 'https://api.telegram.org'                       # Telegram API
    send_resolved: true
    message: '{{ .CommonAnnotations.summary }}\n{{ .CommonAnnotations.description }}'
