name: Bump version

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  bump-version:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install bump2version
      run: pip install bump2version

    - name: Bump version
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        bump2version patch  # или minor, major в зависимости от типа изменения
        git push "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" main