name: Bump version

on:
  push:
    branches:
      - main

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install bump2version
      run: pip install bump2version

    - name: Bump version
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        bump2version patch  # или minor, major в зависимости от типа изменения
        git push origin main